---
- name: Install and configure apache
  hosts: web
  become: yes
  become_method: sudo

  tasks:
    - name: install apache
      yum:
        name: httpd
        state: present
    - name: create index.html and place it under default docroot
      copy:
        src: ./index.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
    - name: start and enable httpd service
      service:
        name: httpd
        state: started
        enabled: yes
